version: '3.8'


services:
  postgres:
    image: postgres:17beta1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D221016855@g
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: